package vn.giapha.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AnniversarySubscriptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnniversarySubscriptionAllPropertiesEquals(AnniversarySubscription expected, AnniversarySubscription actual) {
        assertAnniversarySubscriptionAutoGeneratedPropertiesEquals(expected, actual);
        assertAnniversarySubscriptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnniversarySubscriptionAllUpdatablePropertiesEquals(
        AnniversarySubscription expected,
        AnniversarySubscription actual
    ) {
        assertAnniversarySubscriptionUpdatableFieldsEquals(expected, actual);
        assertAnniversarySubscriptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnniversarySubscriptionAutoGeneratedPropertiesEquals(
        AnniversarySubscription expected,
        AnniversarySubscription actual
    ) {
        assertThat(actual)
            .as("Verify AnniversarySubscription auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnniversarySubscriptionUpdatableFieldsEquals(
        AnniversarySubscription expected,
        AnniversarySubscription actual
    ) {
        assertThat(actual)
            .as("Verify AnniversarySubscription relevant properties")
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getDaysBefore()).as("check daysBefore").isEqualTo(expected.getDaysBefore()))
            .satisfies(a -> assertThat(a.getChannels()).as("check channels").isEqualTo(expected.getChannels()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnniversarySubscriptionUpdatableRelationshipsEquals(
        AnniversarySubscription expected,
        AnniversarySubscription actual
    ) {
        assertThat(actual)
            .as("Verify AnniversarySubscription relationships")
            .satisfies(a -> assertThat(a.getPerson()).as("check person").isEqualTo(expected.getPerson()));
    }
}
