package vn.giapha.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChangeRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChangeRequestAllPropertiesEquals(ChangeRequest expected, ChangeRequest actual) {
        assertChangeRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertChangeRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChangeRequestAllUpdatablePropertiesEquals(ChangeRequest expected, ChangeRequest actual) {
        assertChangeRequestUpdatableFieldsEquals(expected, actual);
        assertChangeRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChangeRequestAutoGeneratedPropertiesEquals(ChangeRequest expected, ChangeRequest actual) {
        assertThat(actual)
            .as("Verify ChangeRequest auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChangeRequestUpdatableFieldsEquals(ChangeRequest expected, ChangeRequest actual) {
        assertThat(actual)
            .as("Verify ChangeRequest relevant properties")
            .satisfies(a -> assertThat(a.getRequesterUserId()).as("check requesterUserId").isEqualTo(expected.getRequesterUserId()))
            .satisfies(a -> assertThat(a.getEntityType()).as("check entityType").isEqualTo(expected.getEntityType()))
            .satisfies(a -> assertThat(a.getSummary()).as("check summary").isEqualTo(expected.getSummary()))
            .satisfies(a -> assertThat(a.getDiffJson()).as("check diffJson").isEqualTo(expected.getDiffJson()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getReviewerNote()).as("check reviewerNote").isEqualTo(expected.getReviewerNote()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getReviewedAt()).as("check reviewedAt").isEqualTo(expected.getReviewedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChangeRequestUpdatableRelationshipsEquals(ChangeRequest expected, ChangeRequest actual) {
        assertThat(actual)
            .as("Verify ChangeRequest relationships")
            .satisfies(a -> assertThat(a.getTree()).as("check tree").isEqualTo(expected.getTree()))
            .satisfies(a -> assertThat(a.getPerson()).as("check person").isEqualTo(expected.getPerson()));
    }
}
