package vn.giapha.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClanEventAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClanEventAllPropertiesEquals(ClanEvent expected, ClanEvent actual) {
        assertClanEventAutoGeneratedPropertiesEquals(expected, actual);
        assertClanEventAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClanEventAllUpdatablePropertiesEquals(ClanEvent expected, ClanEvent actual) {
        assertClanEventUpdatableFieldsEquals(expected, actual);
        assertClanEventUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClanEventAutoGeneratedPropertiesEquals(ClanEvent expected, ClanEvent actual) {
        assertThat(actual)
            .as("Verify ClanEvent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClanEventUpdatableFieldsEquals(ClanEvent expected, ClanEvent actual) {
        assertThat(actual)
            .as("Verify ClanEvent relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getStartSolar()).as("check startSolar").isEqualTo(expected.getStartSolar()))
            .satisfies(a -> assertThat(a.getLunarJson()).as("check lunarJson").isEqualTo(expected.getLunarJson()))
            .satisfies(a -> assertThat(a.getLocation()).as("check location").isEqualTo(expected.getLocation()))
            .satisfies(a -> assertThat(a.getChecklistJson()).as("check checklistJson").isEqualTo(expected.getChecklistJson()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClanEventUpdatableRelationshipsEquals(ClanEvent expected, ClanEvent actual) {
        assertThat(actual)
            .as("Verify ClanEvent relationships")
            .satisfies(a -> assertThat(a.getTree()).as("check tree").isEqualTo(expected.getTree()));
    }
}
