package vn.giapha.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CmsCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCmsCategoryAllPropertiesEquals(CmsCategory expected, CmsCategory actual) {
        assertCmsCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertCmsCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCmsCategoryAllUpdatablePropertiesEquals(CmsCategory expected, CmsCategory actual) {
        assertCmsCategoryUpdatableFieldsEquals(expected, actual);
        assertCmsCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCmsCategoryAutoGeneratedPropertiesEquals(CmsCategory expected, CmsCategory actual) {
        assertThat(actual)
            .as("Verify CmsCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCmsCategoryUpdatableFieldsEquals(CmsCategory expected, CmsCategory actual) {
        assertThat(actual)
            .as("Verify CmsCategory relevant properties")
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getLayout()).as("check layout").isEqualTo(expected.getLayout()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCmsCategoryUpdatableRelationshipsEquals(CmsCategory expected, CmsCategory actual) {
        // empty method
    }
}
