package vn.giapha.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CmsCommentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCmsCommentAllPropertiesEquals(CmsComment expected, CmsComment actual) {
        assertCmsCommentAutoGeneratedPropertiesEquals(expected, actual);
        assertCmsCommentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCmsCommentAllUpdatablePropertiesEquals(CmsComment expected, CmsComment actual) {
        assertCmsCommentUpdatableFieldsEquals(expected, actual);
        assertCmsCommentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCmsCommentAutoGeneratedPropertiesEquals(CmsComment expected, CmsComment actual) {
        assertThat(actual)
            .as("Verify CmsComment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCmsCommentUpdatableFieldsEquals(CmsComment expected, CmsComment actual) {
        assertThat(actual)
            .as("Verify CmsComment relevant properties")
            .satisfies(a -> assertThat(a.getAuthorName()).as("check authorName").isEqualTo(expected.getAuthorName()))
            .satisfies(a -> assertThat(a.getBody()).as("check body").isEqualTo(expected.getBody()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCmsCommentUpdatableRelationshipsEquals(CmsComment expected, CmsComment actual) {
        assertThat(actual)
            .as("Verify CmsComment relationships")
            .satisfies(a -> assertThat(a.getPost()).as("check post").isEqualTo(expected.getPost()));
    }
}
