package vn.giapha.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CmsPostAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCmsPostAllPropertiesEquals(CmsPost expected, CmsPost actual) {
        assertCmsPostAutoGeneratedPropertiesEquals(expected, actual);
        assertCmsPostAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCmsPostAllUpdatablePropertiesEquals(CmsPost expected, CmsPost actual) {
        assertCmsPostUpdatableFieldsEquals(expected, actual);
        assertCmsPostUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCmsPostAutoGeneratedPropertiesEquals(CmsPost expected, CmsPost actual) {
        assertThat(actual)
            .as("Verify CmsPost auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCmsPostUpdatableFieldsEquals(CmsPost expected, CmsPost actual) {
        assertThat(actual)
            .as("Verify CmsPost relevant properties")
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getSummary()).as("check summary").isEqualTo(expected.getSummary()))
            .satisfies(a -> assertThat(a.getBodyHtml()).as("check bodyHtml").isEqualTo(expected.getBodyHtml()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getPublishedAt()).as("check publishedAt").isEqualTo(expected.getPublishedAt()))
            .satisfies(a -> assertThat(a.getViewCount()).as("check viewCount").isEqualTo(expected.getViewCount()))
            .satisfies(a -> assertThat(a.getAuthorName()).as("check authorName").isEqualTo(expected.getAuthorName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCmsPostUpdatableRelationshipsEquals(CmsPost expected, CmsPost actual) {
        assertThat(actual)
            .as("Verify CmsPost relationships")
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()));
    }
}
