package vn.giapha.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DeathAnniversaryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeathAnniversaryAllPropertiesEquals(DeathAnniversary expected, DeathAnniversary actual) {
        assertDeathAnniversaryAutoGeneratedPropertiesEquals(expected, actual);
        assertDeathAnniversaryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeathAnniversaryAllUpdatablePropertiesEquals(DeathAnniversary expected, DeathAnniversary actual) {
        assertDeathAnniversaryUpdatableFieldsEquals(expected, actual);
        assertDeathAnniversaryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeathAnniversaryAutoGeneratedPropertiesEquals(DeathAnniversary expected, DeathAnniversary actual) {
        assertThat(actual)
            .as("Verify DeathAnniversary auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeathAnniversaryUpdatableFieldsEquals(DeathAnniversary expected, DeathAnniversary actual) {
        assertThat(actual)
            .as("Verify DeathAnniversary relevant properties")
            .satisfies(a -> assertThat(a.getLunarDay()).as("check lunarDay").isEqualTo(expected.getLunarDay()))
            .satisfies(a -> assertThat(a.getLunarMonth()).as("check lunarMonth").isEqualTo(expected.getLunarMonth()))
            .satisfies(a -> assertThat(a.getLeapMonth()).as("check leapMonth").isEqualTo(expected.getLeapMonth()))
            .satisfies(a -> assertThat(a.getCanChi()).as("check canChi").isEqualTo(expected.getCanChi()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeathAnniversaryUpdatableRelationshipsEquals(DeathAnniversary expected, DeathAnniversary actual) {
        assertThat(actual)
            .as("Verify DeathAnniversary relationships")
            .satisfies(a -> assertThat(a.getTree()).as("check tree").isEqualTo(expected.getTree()))
            .satisfies(a -> assertThat(a.getPerson()).as("check person").isEqualTo(expected.getPerson()));
    }
}
