package vn.giapha.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static vn.giapha.domain.AssertUtils.bigDecimalCompareTo;

public class DonationCampaignAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonationCampaignAllPropertiesEquals(DonationCampaign expected, DonationCampaign actual) {
        assertDonationCampaignAutoGeneratedPropertiesEquals(expected, actual);
        assertDonationCampaignAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonationCampaignAllUpdatablePropertiesEquals(DonationCampaign expected, DonationCampaign actual) {
        assertDonationCampaignUpdatableFieldsEquals(expected, actual);
        assertDonationCampaignUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonationCampaignAutoGeneratedPropertiesEquals(DonationCampaign expected, DonationCampaign actual) {
        assertThat(actual)
            .as("Verify DonationCampaign auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonationCampaignUpdatableFieldsEquals(DonationCampaign expected, DonationCampaign actual) {
        assertThat(actual)
            .as("Verify DonationCampaign relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a ->
                assertThat(a.getGoalAmount())
                    .as("check goalAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getGoalAmount())
            )
            .satisfies(a ->
                assertThat(a.getRaisedAmount())
                    .as("check raisedAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getRaisedAmount())
            )
            .satisfies(a -> assertThat(a.getVietqrPayload()).as("check vietqrPayload").isEqualTo(expected.getVietqrPayload()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonationCampaignUpdatableRelationshipsEquals(DonationCampaign expected, DonationCampaign actual) {
        assertThat(actual)
            .as("Verify DonationCampaign relationships")
            .satisfies(a -> assertThat(a.getTree()).as("check tree").isEqualTo(expected.getTree()));
    }
}
