package vn.giapha.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static vn.giapha.domain.AssertUtils.bigDecimalCompareTo;

public class DonationContributionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonationContributionAllPropertiesEquals(DonationContribution expected, DonationContribution actual) {
        assertDonationContributionAutoGeneratedPropertiesEquals(expected, actual);
        assertDonationContributionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonationContributionAllUpdatablePropertiesEquals(DonationContribution expected, DonationContribution actual) {
        assertDonationContributionUpdatableFieldsEquals(expected, actual);
        assertDonationContributionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonationContributionAutoGeneratedPropertiesEquals(DonationContribution expected, DonationContribution actual) {
        assertThat(actual)
            .as("Verify DonationContribution auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonationContributionUpdatableFieldsEquals(DonationContribution expected, DonationContribution actual) {
        assertThat(actual)
            .as("Verify DonationContribution relevant properties")
            .satisfies(a -> assertThat(a.getDonorName()).as("check donorName").isEqualTo(expected.getDonorName()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getKind()).as("check kind").isEqualTo(expected.getKind()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonationContributionUpdatableRelationshipsEquals(DonationContribution expected, DonationContribution actual) {
        assertThat(actual)
            .as("Verify DonationContribution relationships")
            .satisfies(a -> assertThat(a.getCampaign()).as("check campaign").isEqualTo(expected.getCampaign()));
    }
}
