package vn.giapha.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EventRsvpAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventRsvpAllPropertiesEquals(EventRsvp expected, EventRsvp actual) {
        assertEventRsvpAutoGeneratedPropertiesEquals(expected, actual);
        assertEventRsvpAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventRsvpAllUpdatablePropertiesEquals(EventRsvp expected, EventRsvp actual) {
        assertEventRsvpUpdatableFieldsEquals(expected, actual);
        assertEventRsvpUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventRsvpAutoGeneratedPropertiesEquals(EventRsvp expected, EventRsvp actual) {
        assertThat(actual)
            .as("Verify EventRsvp auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventRsvpUpdatableFieldsEquals(EventRsvp expected, EventRsvp actual) {
        assertThat(actual)
            .as("Verify EventRsvp relevant properties")
            .satisfies(a -> assertThat(a.getHouseholdName()).as("check householdName").isEqualTo(expected.getHouseholdName()))
            .satisfies(a -> assertThat(a.getHeadcount()).as("check headcount").isEqualTo(expected.getHeadcount()))
            .satisfies(a -> assertThat(a.getVehicles()).as("check vehicles").isEqualTo(expected.getVehicles()))
            .satisfies(a -> assertThat(a.getAssignment()).as("check assignment").isEqualTo(expected.getAssignment()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventRsvpUpdatableRelationshipsEquals(EventRsvp expected, EventRsvp actual) {
        assertThat(actual)
            .as("Verify EventRsvp relationships")
            .satisfies(a -> assertThat(a.getEvent()).as("check event").isEqualTo(expected.getEvent()));
    }
}
