package vn.giapha.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FamilyUnionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyUnionAllPropertiesEquals(FamilyUnion expected, FamilyUnion actual) {
        assertFamilyUnionAutoGeneratedPropertiesEquals(expected, actual);
        assertFamilyUnionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyUnionAllUpdatablePropertiesEquals(FamilyUnion expected, FamilyUnion actual) {
        assertFamilyUnionUpdatableFieldsEquals(expected, actual);
        assertFamilyUnionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyUnionAutoGeneratedPropertiesEquals(FamilyUnion expected, FamilyUnion actual) {
        assertThat(actual)
            .as("Verify FamilyUnion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyUnionUpdatableFieldsEquals(FamilyUnion expected, FamilyUnion actual) {
        assertThat(actual)
            .as("Verify FamilyUnion relevant properties")
            .satisfies(a -> assertThat(a.getOrderNo()).as("check orderNo").isEqualTo(expected.getOrderNo()))
            .satisfies(a -> assertThat(a.getMarriageInfoJson()).as("check marriageInfoJson").isEqualTo(expected.getMarriageInfoJson()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyUnionUpdatableRelationshipsEquals(FamilyUnion expected, FamilyUnion actual) {
        assertThat(actual)
            .as("Verify FamilyUnion relationships")
            .satisfies(a -> assertThat(a.getTree()).as("check tree").isEqualTo(expected.getTree()));
    }
}
