package vn.giapha.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FamilyTreeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyTreeAllPropertiesEquals(FamilyTree expected, FamilyTree actual) {
        assertFamilyTreeAutoGeneratedPropertiesEquals(expected, actual);
        assertFamilyTreeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyTreeAllUpdatablePropertiesEquals(FamilyTree expected, FamilyTree actual) {
        assertFamilyTreeUpdatableFieldsEquals(expected, actual);
        assertFamilyTreeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyTreeAutoGeneratedPropertiesEquals(FamilyTree expected, FamilyTree actual) {
        assertThat(actual)
            .as("Verify FamilyTree auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyTreeUpdatableFieldsEquals(FamilyTree expected, FamilyTree actual) {
        assertThat(actual)
            .as("Verify FamilyTree relevant properties")
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getSurname()).as("check surname").isEqualTo(expected.getSurname()))
            .satisfies(a -> assertThat(a.getBranchName()).as("check branchName").isEqualTo(expected.getBranchName()))
            .satisfies(a -> assertThat(a.getProvinceCode()).as("check provinceCode").isEqualTo(expected.getProvinceCode()))
            .satisfies(a -> assertThat(a.getMetaJson()).as("check metaJson").isEqualTo(expected.getMetaJson()))
            .satisfies(a -> assertThat(a.getStatsCacheJson()).as("check statsCacheJson").isEqualTo(expected.getStatsCacheJson()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFamilyTreeUpdatableRelationshipsEquals(FamilyTree expected, FamilyTree actual) {
        // empty method
    }
}
