package vn.giapha.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MediaAlbumAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaAlbumAllPropertiesEquals(MediaAlbum expected, MediaAlbum actual) {
        assertMediaAlbumAutoGeneratedPropertiesEquals(expected, actual);
        assertMediaAlbumAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaAlbumAllUpdatablePropertiesEquals(MediaAlbum expected, MediaAlbum actual) {
        assertMediaAlbumUpdatableFieldsEquals(expected, actual);
        assertMediaAlbumUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaAlbumAutoGeneratedPropertiesEquals(MediaAlbum expected, MediaAlbum actual) {
        assertThat(actual)
            .as("Verify MediaAlbum auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaAlbumUpdatableFieldsEquals(MediaAlbum expected, MediaAlbum actual) {
        assertThat(actual)
            .as("Verify MediaAlbum relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCoverObjectKey()).as("check coverObjectKey").isEqualTo(expected.getCoverObjectKey()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaAlbumUpdatableRelationshipsEquals(MediaAlbum expected, MediaAlbum actual) {
        // empty method
    }
}
