package vn.giapha.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MediaPhotoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaPhotoAllPropertiesEquals(MediaPhoto expected, MediaPhoto actual) {
        assertMediaPhotoAutoGeneratedPropertiesEquals(expected, actual);
        assertMediaPhotoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaPhotoAllUpdatablePropertiesEquals(MediaPhoto expected, MediaPhoto actual) {
        assertMediaPhotoUpdatableFieldsEquals(expected, actual);
        assertMediaPhotoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaPhotoAutoGeneratedPropertiesEquals(MediaPhoto expected, MediaPhoto actual) {
        assertThat(actual)
            .as("Verify MediaPhoto auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaPhotoUpdatableFieldsEquals(MediaPhoto expected, MediaPhoto actual) {
        assertThat(actual)
            .as("Verify MediaPhoto relevant properties")
            .satisfies(a -> assertThat(a.getObjectKey()).as("check objectKey").isEqualTo(expected.getObjectKey()))
            .satisfies(a -> assertThat(a.getCaption()).as("check caption").isEqualTo(expected.getCaption()))
            .satisfies(a -> assertThat(a.getBlurhash()).as("check blurhash").isEqualTo(expected.getBlurhash()))
            .satisfies(a -> assertThat(a.getViewCount()).as("check viewCount").isEqualTo(expected.getViewCount()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaPhotoUpdatableRelationshipsEquals(MediaPhoto expected, MediaPhoto actual) {
        assertThat(actual)
            .as("Verify MediaPhoto relationships")
            .satisfies(a -> assertThat(a.getAlbum()).as("check album").isEqualTo(expected.getAlbum()));
    }
}
