package vn.giapha.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NotificationOutboxAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationOutboxAllPropertiesEquals(NotificationOutbox expected, NotificationOutbox actual) {
        assertNotificationOutboxAutoGeneratedPropertiesEquals(expected, actual);
        assertNotificationOutboxAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationOutboxAllUpdatablePropertiesEquals(NotificationOutbox expected, NotificationOutbox actual) {
        assertNotificationOutboxUpdatableFieldsEquals(expected, actual);
        assertNotificationOutboxUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationOutboxAutoGeneratedPropertiesEquals(NotificationOutbox expected, NotificationOutbox actual) {
        assertThat(actual)
            .as("Verify NotificationOutbox auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationOutboxUpdatableFieldsEquals(NotificationOutbox expected, NotificationOutbox actual) {
        assertThat(actual)
            .as("Verify NotificationOutbox relevant properties")
            .satisfies(a -> assertThat(a.getChannel()).as("check channel").isEqualTo(expected.getChannel()))
            .satisfies(a -> assertThat(a.getPayloadJson()).as("check payloadJson").isEqualTo(expected.getPayloadJson()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getSentAt()).as("check sentAt").isEqualTo(expected.getSentAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationOutboxUpdatableRelationshipsEquals(NotificationOutbox expected, NotificationOutbox actual) {
        // empty method
    }
}
