package vn.giapha.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PersonAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonAllPropertiesEquals(Person expected, Person actual) {
        assertPersonAutoGeneratedPropertiesEquals(expected, actual);
        assertPersonAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonAllUpdatablePropertiesEquals(Person expected, Person actual) {
        assertPersonUpdatableFieldsEquals(expected, actual);
        assertPersonUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonAutoGeneratedPropertiesEquals(Person expected, Person actual) {
        assertThat(actual)
            .as("Verify Person auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonUpdatableFieldsEquals(Person expected, Person actual) {
        assertThat(actual)
            .as("Verify Person relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getFullName()).as("check fullName").isEqualTo(expected.getFullName()))
            .satisfies(a -> assertThat(a.getTenHuy()).as("check tenHuy").isEqualTo(expected.getTenHuy()))
            .satisfies(a -> assertThat(a.getTenThuong()).as("check tenThuong").isEqualTo(expected.getTenThuong()))
            .satisfies(a -> assertThat(a.getGender()).as("check gender").isEqualTo(expected.getGender()))
            .satisfies(a -> assertThat(a.getLifeStatus()).as("check lifeStatus").isEqualTo(expected.getLifeStatus()))
            .satisfies(a -> assertThat(a.getGeneration()).as("check generation").isEqualTo(expected.getGeneration()))
            .satisfies(a -> assertThat(a.getLineagePath()).as("check lineagePath").isEqualTo(expected.getLineagePath()))
            .satisfies(a -> assertThat(a.getBirthSolar()).as("check birthSolar").isEqualTo(expected.getBirthSolar()))
            .satisfies(a -> assertThat(a.getBirthLunarJson()).as("check birthLunarJson").isEqualTo(expected.getBirthLunarJson()))
            .satisfies(a -> assertThat(a.getDeathSolar()).as("check deathSolar").isEqualTo(expected.getDeathSolar()))
            .satisfies(a -> assertThat(a.getDeathLunarJson()).as("check deathLunarJson").isEqualTo(expected.getDeathLunarJson()))
            .satisfies(a -> assertThat(a.getGraveInfo()).as("check graveInfo").isEqualTo(expected.getGraveInfo()))
            .satisfies(a -> assertThat(a.getGraveLat()).as("check graveLat").isEqualTo(expected.getGraveLat()))
            .satisfies(a -> assertThat(a.getGraveLng()).as("check graveLng").isEqualTo(expected.getGraveLng()))
            .satisfies(a -> assertThat(a.getBiography()).as("check biography").isEqualTo(expected.getBiography()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getPrivacy()).as("check privacy").isEqualTo(expected.getPrivacy()))
            .satisfies(a -> assertThat(a.getLinkedUserId()).as("check linkedUserId").isEqualTo(expected.getLinkedUserId()))
            .satisfies(a -> assertThat(a.getVersion()).as("check version").isEqualTo(expected.getVersion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonUpdatableRelationshipsEquals(Person expected, Person actual) {
        assertThat(actual)
            .as("Verify Person relationships")
            .satisfies(a -> assertThat(a.getTree()).as("check tree").isEqualTo(expected.getTree()));
    }
}
