package vn.giapha.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ScholarshipEntryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScholarshipEntryAllPropertiesEquals(ScholarshipEntry expected, ScholarshipEntry actual) {
        assertScholarshipEntryAutoGeneratedPropertiesEquals(expected, actual);
        assertScholarshipEntryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScholarshipEntryAllUpdatablePropertiesEquals(ScholarshipEntry expected, ScholarshipEntry actual) {
        assertScholarshipEntryUpdatableFieldsEquals(expected, actual);
        assertScholarshipEntryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScholarshipEntryAutoGeneratedPropertiesEquals(ScholarshipEntry expected, ScholarshipEntry actual) {
        assertThat(actual)
            .as("Verify ScholarshipEntry auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScholarshipEntryUpdatableFieldsEquals(ScholarshipEntry expected, ScholarshipEntry actual) {
        assertThat(actual)
            .as("Verify ScholarshipEntry relevant properties")
            .satisfies(a -> assertThat(a.getPersonName()).as("check personName").isEqualTo(expected.getPersonName()))
            .satisfies(a -> assertThat(a.getAchievement()).as("check achievement").isEqualTo(expected.getAchievement()))
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getPersonCode()).as("check personCode").isEqualTo(expected.getPersonCode()))
            .satisfies(a -> assertThat(a.getLevel()).as("check level").isEqualTo(expected.getLevel()))
            .satisfies(a -> assertThat(a.getSchoolOrField()).as("check schoolOrField").isEqualTo(expected.getSchoolOrField()))
            .satisfies(a -> assertThat(a.getMedalNote()).as("check medalNote").isEqualTo(expected.getMedalNote()))
            .satisfies(a -> assertThat(a.getLineageNote()).as("check lineageNote").isEqualTo(expected.getLineageNote()))
            .satisfies(a -> assertThat(a.getReviewNote()).as("check reviewNote").isEqualTo(expected.getReviewNote()))
            .satisfies(a -> assertThat(a.getAwardAmount()).as("check awardAmount").isEqualTo(expected.getAwardAmount()))
            .satisfies(a -> assertThat(a.getAwardedAt()).as("check awardedAt").isEqualTo(expected.getAwardedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScholarshipEntryUpdatableRelationshipsEquals(ScholarshipEntry expected, ScholarshipEntry actual) {
        assertThat(actual)
            .as("Verify ScholarshipEntry relationships")
            .satisfies(a -> assertThat(a.getTree()).as("check tree").isEqualTo(expected.getTree()))
            .satisfies(a -> assertThat(a.getPerson()).as("check person").isEqualTo(expected.getPerson()));
    }
}
