package vn.giapha.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UnionChildAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnionChildAllPropertiesEquals(UnionChild expected, UnionChild actual) {
        assertUnionChildAutoGeneratedPropertiesEquals(expected, actual);
        assertUnionChildAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnionChildAllUpdatablePropertiesEquals(UnionChild expected, UnionChild actual) {
        assertUnionChildUpdatableFieldsEquals(expected, actual);
        assertUnionChildUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnionChildAutoGeneratedPropertiesEquals(UnionChild expected, UnionChild actual) {
        assertThat(actual)
            .as("Verify UnionChild auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnionChildUpdatableFieldsEquals(UnionChild expected, UnionChild actual) {
        assertThat(actual)
            .as("Verify UnionChild relevant properties")
            .satisfies(a -> assertThat(a.getOrderNo()).as("check orderNo").isEqualTo(expected.getOrderNo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnionChildUpdatableRelationshipsEquals(UnionChild expected, UnionChild actual) {
        assertThat(actual)
            .as("Verify UnionChild relationships")
            .satisfies(a -> assertThat(a.getUnion()).as("check union").isEqualTo(expected.getUnion()))
            .satisfies(a -> assertThat(a.getChild()).as("check child").isEqualTo(expected.getChild()));
    }
}
