package vn.giapha.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UnionMemberAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnionMemberAllPropertiesEquals(UnionMember expected, UnionMember actual) {
        assertUnionMemberAutoGeneratedPropertiesEquals(expected, actual);
        assertUnionMemberAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnionMemberAllUpdatablePropertiesEquals(UnionMember expected, UnionMember actual) {
        assertUnionMemberUpdatableFieldsEquals(expected, actual);
        assertUnionMemberUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnionMemberAutoGeneratedPropertiesEquals(UnionMember expected, UnionMember actual) {
        assertThat(actual)
            .as("Verify UnionMember auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnionMemberUpdatableFieldsEquals(UnionMember expected, UnionMember actual) {
        assertThat(actual)
            .as("Verify UnionMember relevant properties")
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnionMemberUpdatableRelationshipsEquals(UnionMember expected, UnionMember actual) {
        assertThat(actual)
            .as("Verify UnionMember relationships")
            .satisfies(a -> assertThat(a.getUnion()).as("check union").isEqualTo(expected.getUnion()))
            .satisfies(a -> assertThat(a.getPerson()).as("check person").isEqualTo(expected.getPerson()));
    }
}
